/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolineablanca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Montoya
 */
public class IngresoPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroP
     */
    /**************************************************************
     * VARIABLES
     ***********************************************************/
    private final String conexion = "jdbc:mysql://localhost/linea_blanca";
    private final String user = "root";
    private final String pass = "";
    private String modeloa, ubicacion;
    private int existencia, seleccionado, operacion;
    private float precio;
    DefaultTableModel modelo;

    /**********************************************************************************************************************************/
    public IngresoPedido() {
        initComponents();
        actualizarTabla();
        modelo = new DefaultTableModel();
        modelo.addColumn("Modelo");
        modelo.addColumn("Existecia");
        modelo.addColumn("Precio");
        modelo.addColumn("Ubicacion");
        modelo.addColumn("Seleccionado");
        JTabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlmacen = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        jScrollPane3 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        btnAgregar = new javax.swing.JButton();
        btnRevisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarSeleccionado = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 3, 20), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel1.setText("Seleccione los productos a continuacion:");

        tablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlmacenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAlmacen);

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "modelo", "existencia", "precio ", "ubicacion", "cantidad"
            }
        ));
        jScrollPane3.setViewportView(JTabla);

        btnAgregar.setBackground(new java.awt.Color(0, 51, 51));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRevisar.setBackground(new java.awt.Color(0, 51, 51));
        btnRevisar.setForeground(new java.awt.Color(255, 255, 255));
        btnRevisar.setText("Revisar");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Lista de productos disponibles");

        jLabel3.setText("Lista de productos añadidos");

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnCantidad.setValue(1);

        jLabel4.setText("Ingrese la cantidad de productos que llevara:");

        btnEliminarSeleccionado.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarSeleccionado.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSeleccionado.setText("Eliminar");
        btnEliminarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(226, 226, 226))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarSeleccionado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(btnRevisar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnAgregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnEliminarSeleccionado)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRevisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(btnAgregar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (modeloa == null) {
            JOptionPane.showMessageDialog(null, "Escoge un producto de los que tenemos disponibles");
        } else {
            seleccionado = Integer.parseInt(spnCantidad.getValue().toString());
            operacion = existencia - seleccionado;
            Object datos2[] = { modeloa, operacion, precio, ubicacion, seleccionado };
            modelo.addRow(datos2);
            spnCantidad.setValue(1);
            
            actualizarBase(operacion);
        }
    }

    private void tablaAlmacenMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Object valor_constante = tablaAlmacen.getValueAt(tablaAlmacen.getSelectedRow(), 0);
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            sts.execute("SELECT * FROM almacen WHERE modelo = '" + String.valueOf(valor_constante) + "';");
            ResultSet rs = sts.getResultSet();
            if (rs.next()) {
                modeloa = rs.getString("modelo");
                existencia = rs.getInt("cant_Exist");
                precio = rs.getFloat("precio_uni");
                ubicacion = rs.getString("ubicacion");
            }
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
    }

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRevisarActionPerformed
        // TODO add your handling code here:
        if (JTabla.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un producto por lo menos para poder continuar");
        } else {
            // Codigo para mandar la tabla con elementos seleccionados a la otra
            RevisionPedido internal1 = new RevisionPedido();
            LBDesktop.desktopInicio.add(internal1);
            internal1.show();
            this.setVisible(false);
            for (int i = 0; i < JTabla.getRowCount(); i++) {
                String dat[] = new String[5];
                dat[0] = JTabla.getValueAt(i, 0).toString();
                dat[1] = JTabla.getValueAt(i, 2).toString();
                dat[2] = JTabla.getValueAt(i, 4).toString();
                dat[3] = String.valueOf(Float.parseFloat(JTabla.getValueAt(i, 2).toString())
                        * Float.parseFloat(JTabla.getValueAt(i, 4).toString()));
                RevisionPedido.modelo2.addRow(dat);
            }
        }
    }// GEN-LAST:event_btnRevisarActionPerformed

    private void btnEliminarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarSeleccionadoActionPerformed
        // TODO add your handling code here:
        int seleccionado = JTabla.getSelectedRow();
        String cantidadG = String.valueOf(modelo.getValueAt(JTabla.getSelectedRow(), 4));
        String existenciaG = String.valueOf(modelo.getValueAt(JTabla.getSelectedRow(), 1));
        operacion = Integer.parseInt(existenciaG) + Integer.parseInt(cantidadG);
        if (seleccionado >= 0) {
            actualizarBase(operacion);
            modelo.removeRow(seleccionado);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el producto que va a quitar");
        }
    }

    /******************************************************
     * FUNCIONES CREADAS
     ***************************************************************/
    public void actualizarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        ArrayList<ArrayList<Object>> lista = new ArrayList<>();
        Object datos[] = new Object[4];
        int i = 0;
        model.addColumn("Modelo");
        model.addColumn("Total, en existencia");
        model.addColumn("Precio unitario");
        model.addColumn("Ubicación en almacén");
        this.tablaAlmacen.setModel(model);
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            sts.execute("SELECT * FROM almacen");
            ResultSet rs = sts.getResultSet();
            while (rs.next()) {
                lista.add(new ArrayList<>());
                lista.get(i).add(rs.getString("modelo"));
                lista.get(i).add(rs.getInt("cant_Exist"));
                lista.get(i).add(rs.getInt("precio_uni"));
                lista.get(i).add(rs.getString("ubicacion"));
                i++;
            }
            for (int j = 0; j < lista.size(); j++) {
                datos[0] = lista.get(j).get(0);
                datos[1] = lista.get(j).get(1);
                datos[2] = lista.get(j).get(2);
                datos[3] = lista.get(j).get(3);
                model.addRow(datos);
            }
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
    }

    public void actualizarBase(int op) {
        System.out.println(op);
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            String update = "UPDATE almacen set cant_Exist = " + op + " WHERE modelo = '" + modeloa + "';";
            sts.executeUpdate(update);
            conn.close();
            actualizarTabla();
        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTabla;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminarSeleccionado;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tablaAlmacen;
    // End of variables declaration//GEN-END:variables
}
