/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolineablanca;

import com.itextpdf.text.BaseColor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Montoya
 */
public class RevisionPedido extends javax.swing.JInternalFrame implements Runnable {

    /**
     * Creates new form RevisionPedido
     */
    /**
     * ************************************************************
     * VARIABLES
     **********************************************************
     */
    static DefaultTableModel modelo2;
    private int pedido = (int) Math.floor(Math.random() * (99999 - 00000 + 1) + 00000);
    private Thread db1, db2, db3;
    private float total;
    private final String conexion = "jdbc:mysql://localhost/linea_blanca", user = "root", pass = "";
    private String nombreC, apPaterno, apMaterno, correoC, coloniaC, munC, calleC;
    private int idRFC, noExtC, noIntC, CPC;
    private long telC;
    Calendar fecha = Calendar.getInstance();
    String dat[] = new String[5];
    Object datos[] = new Object[5];

    /**
     * *******************************************************************************************************************************
     */
    public RevisionPedido() {
        initComponents();
        modelo2 = new DefaultTableModel();
        modelo2.addColumn("Modelo");
        modelo2.addColumn("Precio unitario");
        modelo2.addColumn("Cantidad");
        modelo2.addColumn("Subtotal");
        jTablaFinal.setModel(modelo2);
        desFormulario();
        inicio();
        btnPDF.setVisible(false);
        txtRFCAdmin.setText(String.valueOf(InicioSesion.idAdmin));
        txtRFCAdmin.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumeroPedido = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaFinal = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        txtCorreo = new javax.swing.JTextField();
        btnGuardarC = new javax.swing.JButton();
        lblCorreoR = new javax.swing.JLabel();
        lblResponsable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtExterior = new javax.swing.JTextField();
        txtInterior = new javax.swing.JTextField();
        txtCodigoP = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRFCAdmin = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTablaClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE PEDIDO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 3, 20), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel1.setText("Número de pedido:");

        jLabel2.setText("Nombre del cliente: ");

        jLabel3.setText("Teléfono:");

        jLabel4.setText("Correo electrónico:");

        jLabel5.setText("Estado:");

        jLabel6.setText("Responsable:");

        lblNumeroPedido.setText("jLabel7");

        lblEstado.setText("Activo");

        jTablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaFinal);

        btnGuardarC.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardarC.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarC.setText("Guardar");
        btnGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCActionPerformed(evt);
            }
        });

        jLabel7.setText("Apellido paterno:");

        jLabel8.setText("Apellido materno:");

        jLabel9.setText("Colonia:");

        jLabel10.setText("Municipio:");

        jLabel11.setText("Calle:");

        jLabel12.setText("No. Exterior:");

        jLabel13.setText("No. Interior:");

        jLabel14.setText("Codigo Postal:");

        jLabel15.setText("RFC:");

        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFCKeyReleased(evt);
            }
        });

        jLabel16.setText("Id responsable:");

        btnPDF.setBackground(new java.awt.Color(255, 153, 51));
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("Generar PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        JTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTablaClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(67, 67, 67)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(55, 55, 55)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel12)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jLabel13)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(txtInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel14)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel10)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(520, 520, 520)
                                        .addComponent(lblCorreoR, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRFCAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblNumeroPedido))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(425, 425, 425)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblEstado))
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(292, 292, 292))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNumeroPedido)
                    .addComponent(lblEstado)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtRFCAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(lblResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(lblCorreoR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarC)
                    .addComponent(btnPDF))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarCActionPerformed
        // TODO add your handling code here: REGISTRAR TABLA CLIENTE, REGISTRAR
        // DETALLEXPEDIDO
        for (int i = 0; i < jTablaFinal.getRowCount(); i++) {
            datos[0] = jTablaFinal.getValueAt(i, 0);
            datos[1] = jTablaFinal.getValueAt(i, 1);
            datos[2] = jTablaFinal.getValueAt(i, 2);
            datos[3] = String.valueOf(jTablaFinal.getValueAt(i, 3));
            total += Float.parseFloat(datos[3].toString());
        }
        if (validarEmail(txtCorreo.getText())) {
            if (nombreC != null) {
                // UPDATE
                if (Long.parseLong(txtTelefono.getText()) != telC || txtCorreo.getText().equals(correoC) == false || txtColonia.getText().equals(coloniaC)== false || txtMunicipio.getText().equals(munC)== false || txtCalle.getText().equals(calleC)== false || Integer.parseInt(txtExterior.getText()) != noExtC || Integer.parseInt(txtInterior.getText()) != noIntC || Integer.parseInt(txtCodigoP.getText()) != CPC) {
                    db2 = new Thread(this, "registrou"); // Comienzo del hilo
                    db2.start();                    
                }
                db3 = new Thread(this, "registrop");
                db3.start();
                
                try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
                    for (int i = 0; i < jTablaFinal.getRowCount(); i++) {
                        Statement sts = conn.createStatement();
                        dat[0] = jTablaFinal.getValueAt(i, 0).toString();
                        dat[1] = jTablaFinal.getValueAt(i, 1).toString();
                        dat[2] = jTablaFinal.getValueAt(i, 2).toString();
                        dat[3] = jTablaFinal.getValueAt(i, 3).toString();
                        sts.addBatch(
                                "INSERT INTO detallexpedido (id_detalleP,no_pedido, modelo, cantidad, subtotal) VALUES (NULL,"
                                + Integer.parseInt(lblNumeroPedido.getText()) + ",'" + String.valueOf(dat[0])
                                + "'," + Integer.parseInt(dat[2]) + "," + Float.parseFloat(dat[3]) + ");");
                        sts.executeBatch();
                    }
                    JOptionPane.showMessageDialog(null, "Datos almacenados exitosamente");
                    btnPDF.setVisible(true);
                    conn.close();
                } catch (SQLException ex) {
                    System.out.println("tambien tira aqui");
                    System.out.println(ex);
                    System.out.println("tambien tira aqui");
                }
            } else {
                System.out.println("ENTRA AL REGISTRO NUEVO");
                db1 = new Thread(this, "registroc"); // Comienzo del hilo
                db1.start();
                db3 = new Thread(this, "registrop");
                db3.start();
                
                try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
                    for (int i = 0; i < jTablaFinal.getRowCount(); i++) {
                        Statement sts = conn.createStatement();
                        dat[0] = jTablaFinal.getValueAt(i, 0).toString();
                        dat[1] = jTablaFinal.getValueAt(i, 1).toString();
                        dat[2] = jTablaFinal.getValueAt(i, 2).toString();
                        dat[3] = jTablaFinal.getValueAt(i, 3).toString();
                        sts.addBatch(
                                "INSERT INTO detallexpedido (id_detalleP,no_pedido, modelo, cantidad, subtotal) VALUES (NULL,"
                                + Integer.parseInt(lblNumeroPedido.getText()) + ",'" + String.valueOf(dat[0])
                                + "'," + Integer.parseInt(dat[2]) + "," + Float.parseFloat(dat[3]) + ");");
                        sts.executeBatch();
                    }
                    JOptionPane.showMessageDialog(null, "Datos almacenados exitosamente");
                    btnPDF.setVisible(true);
                    conn.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un correo valido ejemplo: user@us21.com");
        }
    }// GEN-LAST:event_btnGuardarCActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        Document doc = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(doc, new FileOutputStream(ruta
                    + "/Documents/Universidad4/Programacion_III/NetBeansProjects/proyectoLineaBlanca/pdfGuardado/ReporteCompra.pdf"));
            Image imagen = Image.getInstance("src/proyectolineablanca/fondoPDF.jpeg");
            doc.open();
            doc.add(new Paragraph("\n\n\n\n\n\n\n"));
            doc.add(new Paragraph("                   REPORTE DE COMPRA DE USUARIO\n\n", FontFactory.getFont("Consolas", 18, BaseColor.BLACK)));
            doc.add(new Paragraph("                                    " + String.valueOf(lblNumeroPedido.getText()) + "                                             " + new Date().toString()));
            doc.add(new Paragraph("Cliente: " + txtNombre.getText() + "  " + " Responsable de la venta: " + String.valueOf(lblResponsable.getText())));
            doc.add(new Paragraph("Telefono: " + String.valueOf(txtTelefono.getText()) + "  " + "Correo electronico de responsable: " + lblCorreoR.getText()));
            doc.add(new Paragraph("Correo electronico: " + txtCorreo.getText()));
            doc.add(new Paragraph(
                    "----------------------------------------------------------------------------------------------------------------------------------\n\n"));
            imagen.scaleAbsoluteHeight(850f);
            imagen.scaleAbsoluteWidth(600f);
            imagen.setAbsolutePosition(0f, 0f);
            doc.add(imagen);
            PdfPTable tab = new PdfPTable(5);
            tab.addCell("Id pedido");
            tab.addCell("No. pedido");
            tab.addCell("Modelo");
            tab.addCell("Cantidad");
            tab.addCell("Subtotal");
            try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
                Statement sts = conn.createStatement();
                sts.execute("SELECT * FROM detallexpedido WHERE no_pedido = "
                        + Integer.parseInt(lblNumeroPedido.getText()) + ";");
                ResultSet rs = sts.getResultSet();
                if (rs.next()) {
                    do {
                        tab.addCell(rs.getString(1));
                        tab.addCell(rs.getString(2));
                        tab.addCell(rs.getString(3));
                        tab.addCell(rs.getString(4));
                        tab.addCell(rs.getString(5));
                    } while (rs.next());
                    doc.add(tab);
                }
                conn.close();
            } catch (DocumentException | SQLException ex) {
                System.out.println(ex);
            }
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte creado");
        } catch (DocumentException | HeadlessException | FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException exx) {
            System.out.println(exx);
        }
        Path path = Paths.get(
                "C:/Users/Luis Montoya/Documents/Universidad4/Programacion_III/NetBeansProjects/proyectoLineaBlanca/pdfGuardado",
                "ReporteCompra.pdf");
        if (!Files.exists(path)) {
            System.out.printf("el archivo < %s > no existe", path.toString());
        } else {
            try {
                Desktop.getDesktop().open(path.toFile());
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
    }// GEN-LAST:event_btnPDFActionPerformed

    private void txtRFCKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtRFCKeyReleased
        // TODO add your handling code here:
        String tecla = KeyEvent.getKeyText(evt.getKeyCode());
        filtrarDatos(txtRFC.getText(), tecla);
    }// GEN-LAST:event_txtRFCKeyReleased

    private void JTablaClientesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_JTablaClientesMouseClicked
        // TODO add your handling code here:
        Object valor_constante = JTablaClientes.getValueAt(JTablaClientes.getSelectedRow(), 0);
        System.out.println(valor_constante);
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            sts.execute("SELECT * FROM cliente WHERE id_RFCliente = " + valor_constante + ";");
            ResultSet rs = sts.getResultSet();
            if (rs.next()) {
                idRFC = rs.getInt("id_RFCliente");
                nombreC = rs.getString("nombre");
                apPaterno = rs.getString("ap_paterno");
                apMaterno = rs.getString("ap_materno");
                telC = rs.getLong("telefono");
                correoC = rs.getString("correo");
                coloniaC = rs.getString("colonia");
                munC = rs.getString("municipio");
                calleC = rs.getString("calle");
                noExtC = rs.getInt("no_exterior");
                noIntC = rs.getInt("no_interior");
                CPC = rs.getInt("codigo_postal");
            }
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
        if (nombreC != null) {
            actFormulario();
        }
    }

    /**
     * ************************************************************
     * HILOS
     **********************************************************
     */
    @Override
    public void run() {
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            if (Thread.currentThread().getName().equals("registroc")) {
                Statement sts = conn.createStatement();
                sts.addBatch(
                        "INSERT INTO cliente (id_RFCliente, nombre, ap_paterno, ap_materno, telefono, correo, colonia, municipio, calle, no_exterior, no_interior, codigo_postal) VALUES ("
                        + Integer.parseInt(txtRFC.getText()) + ",'" + txtNombre.getText() + "', '"
                        + txtPaterno.getText() + "' , '" + txtMaterno.getText() + "', "
                        + Long.valueOf(txtTelefono.getText()) + ", '" + txtCorreo.getText() + "' , '"
                        + txtColonia.getText() + "', '" + txtMunicipio.getText() + "','" + txtCalle.getText()
                        + "'," + Integer.parseInt(txtExterior.getText()) + ","
                        + Integer.parseInt(txtInterior.getText()) + "," + Integer.parseInt(txtCodigoP.getText())
                        + ");");
                sts.executeBatch();
            }
            if (Thread.currentThread().getName().equals("registrou")) {
                Statement sts = conn.createStatement();
                String upd = "UPDATE cliente SET telefono = '" + Long.valueOf(txtTelefono.getText()) + "', correo = '"
                        + txtCorreo.getText() + "', colonia = '" + txtColonia.getText() + "', municipio = '"
                        + txtMunicipio.getText() + "', calle = '" + txtCalle.getText() + "', no_exterior = "
                        + Integer.parseInt(txtExterior.getText()) + ", no_interior = "
                        + Integer.parseInt(txtInterior.getText()) + ", codigo_postal = "
                        + Integer.parseInt(txtCodigoP.getText()) + " WHERE id_RFCliente = "
                        + Integer.parseInt(txtRFC.getText()) + ";";
                sts.executeUpdate(upd);
            }
            if (Thread.currentThread().getName().equals("registrop")) {
                Statement sts = conn.createStatement();
                sts.addBatch(
                        "INSERT INTO pedido (no_pedido, id_RFCliente, id_RFCAdmn, mes, dia, anio, total, estado) VALUES ("
                        + Integer.parseInt(lblNumeroPedido.getText()) + "," + Integer.parseInt(txtRFC.getText())
                        + "," + Integer.parseInt(txtRFCAdmin.getText()) + "," + (fecha.get(Calendar.MONTH) + 1) + ","
                        + fecha.get(Calendar.DAY_OF_MONTH) + "," + fecha.get(Calendar.YEAR) + "," + total + ",'"
                        + lblEstado.getText() + "');");
                sts.executeBatch();
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (NumberFormatException nEx) {
            System.out.println(nEx);
            JOptionPane.showMessageDialog(null, "Ingrese datos numericos en los datos donde se le solicita");
        }
    }

    /**
     * ****************************************************
     * FUNCIONES CREADAS
     **************************************************************
     */
    public boolean validarEmail(String email) {
        String emailC = "^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@" + "[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4})$";
        Pattern patron = Pattern.compile(emailC);
        if (email != null) {
            Matcher matcher = patron.matcher(email);
            if (matcher.find()) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
    
    public void filtrarDatos(String valor, String tecla) {
        String[] titulos = {"id_RFCliente", "nombre", "ap_paterno", "ap_materno", "telefono", "correo", "colonia",
            "municipio", "calle", "no_exterior", "no_interior", "codigo_postal"};
        String[] registros = new String[12];
        DefaultTableModel modelo3 = new DefaultTableModel(null, titulos);
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            sts.execute("SELECT * FROM cliente WHERE id_RFCliente LIKE '%" + valor + "%';");
            ResultSet rs = sts.getResultSet();
            while (rs.next()) {
                registros[0] = rs.getString("id_RFCliente");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("ap_paterno");
                registros[3] = rs.getString("ap_materno");
                registros[4] = rs.getString("telefono");
                registros[5] = rs.getString("correo");
                registros[6] = rs.getString("colonia");
                registros[7] = rs.getString("municipio");
                registros[8] = rs.getString("calle");
                registros[9] = rs.getString("no_exterior");
                registros[10] = rs.getString("no_interior");
                registros[11] = rs.getString("codigo_postal");
                modelo3.addRow(registros);
            }
            if (!rs.next() && tecla != "Retroceso") {
                reactFormulario();
            } else {
                desFormulario();
            }
            JTablaClientes.setModel(modelo3);
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void desFormulario() {
        txtNombre.setEditable(false);
        txtNombre.setText("");
        txtPaterno.setEditable(false);
        txtPaterno.setText("");
        txtMaterno.setEditable(false);
        txtMaterno.setText("");
        txtTelefono.setEditable(false);
        txtTelefono.setText("");
        txtCorreo.setEditable(false);
        txtCorreo.setText("");
        txtColonia.setEditable(false);
        txtColonia.setText("");
        txtMunicipio.setEditable(false);
        txtMunicipio.setText("");
        txtCalle.setEditable(false);
        txtCalle.setText("");
        txtExterior.setEditable(false);
        txtExterior.setText("");
        txtInterior.setEditable(false);
        txtInterior.setText("");
        txtCodigoP.setEditable(false);
        txtCodigoP.setText("");
        btnGuardarC.setEnabled(false);
    }
    
    public void reactFormulario() {
        txtNombre.setEditable(true);
        txtNombre.setText("");
        txtPaterno.setEditable(true);
        txtPaterno.setText("");
        txtMaterno.setEditable(true);
        txtMaterno.setText("");
        txtTelefono.setEditable(true);
        txtTelefono.setText("");
        txtCorreo.setEditable(true);
        txtCorreo.setText("");
        txtColonia.setEditable(true);
        txtColonia.setText("");
        txtMunicipio.setEditable(true);
        txtMunicipio.setText("");
        txtCalle.setEditable(true);
        txtCalle.setText("");
        txtExterior.setEditable(true);
        txtExterior.setText("");
        txtInterior.setEditable(true);
        txtInterior.setText("");
        txtCodigoP.setEditable(true);
        txtCodigoP.setText("");
        btnGuardarC.setEnabled(true);
    }
    
    public void actFormulario() {
        txtRFC.setText(String.valueOf(idRFC));
        txtNombre.setEditable(false);
        txtNombre.setText(nombreC);
        txtPaterno.setEditable(false);
        txtPaterno.setText(apPaterno);
        txtMaterno.setEditable(false);
        txtMaterno.setText(apMaterno);
        txtTelefono.setEditable(true);
        txtTelefono.setText(String.valueOf(telC));
        txtCorreo.setEditable(true);
        txtCorreo.setText(correoC);
        txtColonia.setEditable(true);
        txtColonia.setText(coloniaC);
        txtMunicipio.setEditable(true);
        txtMunicipio.setText(munC);
        txtCalle.setEditable(true);
        txtCalle.setText(calleC);
        txtExterior.setEditable(true);
        txtExterior.setText(String.valueOf(noExtC));
        txtInterior.setEditable(true);
        txtInterior.setText(String.valueOf(noIntC));
        txtCodigoP.setEditable(true);
        txtCodigoP.setText(String.valueOf(CPC));
        btnGuardarC.setEnabled(true);
    }
    
    public void inicio() {
        lblNumeroPedido.setText(String.valueOf(pedido));
        lblResponsable.setText(InicioSesion.usuario);
        lblCorreoR.setText(InicioSesion.correo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaClientes;
    private javax.swing.JButton btnGuardarC;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaFinal;
    private javax.swing.JLabel lblCorreoR;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumeroPedido;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtExterior;
    private javax.swing.JTextField txtInterior;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtRFCAdmin;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
