/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolineablanca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Montoya
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    /**
     * ************************************************************
     * VARIABLES *********************************************************
     */
    private final String conexion = "jdbc:mysql://localhost/linea_blanca";
    private final String user = "root";
    private final String pass = "";
    DefaultTableModel modelo;
    String[] titulos = {"Id RFC Admin", "Nombre", "Apellido paterno", "Apellido materno", "Correo", "Contraseña", "Estado"};

    /**
     * *******************************************************************************************************************************
     */
    public Usuario() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Operaciones usuarios");
        txtActnombre.setEditable(false);
        txtActpaterno.setEditable(false);
        txtActmaterno.setEditable(false);
        desactivarFormulario();
        modelo = new DefaultTableModel(null, titulos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtBusqNombre = new javax.swing.JTextField();
        txtBusqRFC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtActnombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtActpaterno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtActmaterno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtActcorreo = new javax.swing.JTextField();
        txtActcontra = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        comboBestado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAmaterno = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        txtApaterno = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtIDRFC = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("jTextField1");

        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERACIONES USUARIOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 3, 22), new java.awt.Color(51, 0, 0))); // NOI18N

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolineablanca/shutdown.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 3, 20), new java.awt.Color(0, 51, 51))); // NOI18N

        jTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablaUsuarios);

        jLabel1.setText("ID RFC:");

        jLabel2.setText("Nombre:");

        btnEliminar.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBusqNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqNombreKeyReleased(evt);
            }
        });

        txtBusqRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqRFCKeyReleased(evt);
            }
        });

        jLabel10.setText("Nombre:");

        jLabel11.setText("Apellido paterno:");

        jLabel12.setText("Apellido materno:");

        jLabel13.setText("Correo:");

        jLabel14.setText("Estado:");

        jLabel15.setText("Contraseña: ");

        comboBestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnActualizar.setBackground(new java.awt.Color(0, 51, 51));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtBusqRFC))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBusqNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtActnombre)
                            .addComponent(txtActpaterno)
                            .addComponent(txtActmaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtActcontra)
                            .addComponent(txtActcorreo)
                            .addComponent(comboBestado, 0, 190, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusqRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusqNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnEliminar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtActnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtActcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtActpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtActmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(comboBestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 3, 20), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel3.setText("ID RFC:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido paterno:");

        jLabel6.setText("Apellido materno:");

        jLabel7.setText("Correo:");

        jLabel8.setText("Contraseña:");

        jLabel9.setText("Estado:");

        txtIDRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDRFCActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 51));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblEstado.setText("Activo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApaterno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))))
                .addGap(82, 82, 82)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnRegistrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblEstado))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusqRFCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqRFCKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() != 8) {
            filtrarDatos(String.valueOf(txtBusqRFC.getText()), 1);
        } else {
            filtrarDatos(null, 3);
        }
    }//GEN-LAST:event_txtBusqRFCKeyReleased

    private void txtBusqNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqNombreKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() != 8) {
            filtrarDatos(txtBusqNombre.getText(), 2);
        }
    }//GEN-LAST:event_txtBusqNombreKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int seleccionado = jTablaUsuarios.getSelectedRow();
        String eliminar = String.valueOf(modelo.getValueAt(jTablaUsuarios.getSelectedRow(), 1));
        if (seleccionado >= 0) {
            try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
                Statement sts = conn.createStatement();
                sts.execute("DELETE FROM admn WHERE nombre = '" + eliminar + "';");
                ResultSet rs = sts.getResultSet();
                JOptionPane.showMessageDialog(null, "Se ha eliminado el usuario");
                txtActnombre.setText("");
                txtActpaterno.setText("");
                txtActmaterno.setText("");
                txtActcorreo.setText("");
                txtActcontra.setText("");
                conn.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            modelo.removeRow(seleccionado);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el usuario que va a eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaUsuariosMouseClicked
        // TODO add your handling code here:
        Object valor_constante = jTablaUsuarios.getValueAt(jTablaUsuarios.getSelectedRow(), 0);
        System.out.println(valor_constante);
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            sts.execute("SELECT * FROM admn WHERE id_RFCAdmn = " + Integer.parseInt(String.valueOf(valor_constante)) + ";");
            ResultSet rs = sts.getResultSet();
            if (rs.next()) {
                txtBusqRFC.setText(String.valueOf(rs.getInt("id_RFCAdmn")));
                txtActnombre.setText(rs.getString("nombre"));
                txtActpaterno.setText(rs.getString("ap_paterno"));
                txtActmaterno.setText(rs.getString("ap_materno"));
                txtActcorreo.setText(rs.getString("correo"));
                txtActcontra.setText(rs.getString("contrasenia"));
            }
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
    }//GEN-LAST:event_jTablaUsuariosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            try {
                String update = "UPDATE admn set correo = '" + txtActcorreo.getText() + "', contrasenia = '"
                        + txtActcontra.getText() + "', estado = '"
                        + String.valueOf(comboBestado.getSelectedItem()) + "' WHERE nombre = '" + txtActnombre.getText() + "';";
                sts.executeUpdate(update);
                conn.close();
                JOptionPane.showMessageDialog(null, "Datos actualizados");
                txtActnombre.setText("");
                txtActpaterno.setText("");
                txtActmaterno.setText("");
                txtActcorreo.setText("");
                txtActcontra.setText("");
                filtrarDatos(null, 3);
            } catch (NumberFormatException err) {
            }

        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        new InicioSesion().setVisible(true);
    }

    private void txtIDRFCActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            Statement sts = conn.createStatement();
            sts.execute("SELECT * FROM admn WHERE id_RFCAdmn = '" + Integer.valueOf(txtIDRFC.getText()) + "';");
            ResultSet rs = sts.getResultSet();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Este usuario ya existe");
            } else {
                activarFormulario();
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros por favor");
            System.out.println(ex);
            System.out.println(ex.getNextException());
        }
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (validarEmail(txtCorreo.getText())) {
            if (txtNombre.getText().equals("") || txtApaterno.getText().equals("") || txtAmaterno.getText().equals("") || txtContra.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Rellene los campos por favor!");
            } else {
                try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
                    Statement sts = conn.createStatement();
                    sts.addBatch(
                            "INSERT INTO admn(id_RFCAdmn, nombre, ap_paterno, ap_materno, correo, contrasenia, estado) VALUES ("
                            + Integer.parseInt(txtIDRFC.getText()) + ", '" + txtNombre.getText() + "', '"
                            + txtApaterno.getText() + "', '" + txtAmaterno.getText() + "', '" + txtCorreo.getText()
                            + "', '" + txtContra.getText() + "', '" + lblEstado.getText() + "');");
                    sts.executeBatch();
                    conn.close();
                    JOptionPane.showMessageDialog(null, "El usuario se ha registrado correctamente");
                    limpiarFormulario();
                    filtrarDatos(null, 3);
                } catch (SQLException ex) {
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un correo valido");
        }
    }

    /**
     * ****************************************************
     * FUNCIONES CREADAS
     * *************************************************************
     */
    public void filtrarDatos(String valor, int num) {
        try (Connection conn = DriverManager.getConnection(conexion, user, pass)) {
            switch (num) {
                case 1: {
                    String[] registros = new String[7];
                    modelo = new DefaultTableModel(null, titulos);
                    Statement sts = conn.createStatement();
                    sts.execute("SELECT * FROM admn WHERE id_RFCAdmn LIKE '%" + valor + "%' AND id_RFCAdmn > 1;");
                    ResultSet rs = sts.getResultSet();
                    while (rs.next()) {
                        registros[0] = rs.getString("id_RFCAdmn");
                        registros[1] = rs.getString("nombre");
                        registros[2] = rs.getString("ap_paterno");
                        registros[3] = rs.getString("ap_materno");
                        registros[4] = rs.getString("correo");
                        registros[5] = rs.getString("contrasenia");
                        registros[6] = rs.getString("estado");
                        modelo.addRow(registros);
                    }
                    jTablaUsuarios.setModel(modelo);
                    conn.close();
                    break;
                }
                case 2: {
                    String[] registros = new String[7];
                    modelo = new DefaultTableModel(null, titulos);
                    Statement sts = conn.createStatement();
                    sts.execute("SELECT * FROM admn WHERE nombre LIKE '%" + valor + "%' AND id_RFCAdmn > 1;");
                    ResultSet rs = sts.getResultSet();
                    while (rs.next()) {
                        registros[0] = rs.getString("id_RFCAdmn");
                        registros[1] = rs.getString("nombre");
                        registros[2] = rs.getString("ap_paterno");
                        registros[3] = rs.getString("ap_materno");
                        registros[4] = rs.getString("correo");
                        registros[5] = rs.getString("contrasenia");
                        registros[6] = rs.getString("estado");
                        modelo.addRow(registros);
                    }
                    jTablaUsuarios.setModel(modelo);
                    conn.close();
                    break;
                }
                case 3:
                    String[] registros = new String[7];
                    modelo = new DefaultTableModel(null, titulos);
                    Statement sts = conn.createStatement();
                    sts.execute("SELECT * FROM admn WHERE id_RFCAdmn > 1;");
                    ResultSet rs = sts.getResultSet();
                    while (rs.next()) {
                        registros[0] = rs.getString("id_RFCAdmn");
                        registros[1] = rs.getString("nombre");
                        registros[2] = rs.getString("ap_paterno");
                        registros[3] = rs.getString("ap_materno");
                        registros[4] = rs.getString("correo");
                        registros[5] = rs.getString("contrasenia");
                        registros[6] = rs.getString("estado");
                        modelo.addRow(registros);
                    }
                    jTablaUsuarios.setModel(modelo);
                    conn.close();
                    break;
                default:
                    break;
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public boolean validarEmail(String email) {
        String emailC = "^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@" + "[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4})$";
        Pattern patron = Pattern.compile(emailC);
        if (email != null) {
            Matcher matcher = patron.matcher(email);
            if (matcher.find()) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }

    public void desactivarFormulario() {
        txtNombre.setEditable(false);
        txtApaterno.setEditable(false);
        txtAmaterno.setEditable(false);
        txtCorreo.setEditable(false);
        txtContra.setEditable(false);
        btnRegistrar.setEnabled(false);
    }

    public void activarFormulario() {
        txtNombre.setEditable(true);
        txtApaterno.setEditable(true);
        txtAmaterno.setEditable(true);
        txtCorreo.setEditable(true);
        txtContra.setEditable(true);
        btnRegistrar.setEnabled(true);
    }

    public void limpiarFormulario() {
        txtNombre.setText("");
        txtApaterno.setText("");
        txtAmaterno.setText("");
        txtCorreo.setText("");
        txtContra.setText("");
        btnRegistrar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code">
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboBestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaUsuarios;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JPasswordField txtActcontra;
    private javax.swing.JTextField txtActcorreo;
    private javax.swing.JTextField txtActmaterno;
    private javax.swing.JTextField txtActnombre;
    private javax.swing.JTextField txtActpaterno;
    private javax.swing.JTextField txtAmaterno;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JTextField txtBusqNombre;
    private javax.swing.JTextField txtBusqRFC;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIDRFC;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
